# Create
post {{hostname}}/category/create
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=XXX

--XXX
Content-Disposition: form-data; name="data"
Content-Type: text/plain

{
  "name": "Saúde",
  "priority": 1,
  "backgroundColor": "#E8CBAA"
}

--XXX
Content-Disposition: form-data; name="image"; filename="image.jpeg"
Content-Type: image/jpeg

< ./image.jpeg

--XXX--
